# detect license plates on the 2 cameras that have clear shots
#  no successful hits yet, but haven't tried hard
- platform: openalpr_cloud
  api_key: !secret openalpr_cloud_key
  region: us
  source: 
    - entity_id: camera.garage_back_west
    - entity_id: camera.garage_back_east
#
# somewhat reliabily indicates whether or not it sees a face. 
#  I'm impressed.  It can trigger a second stage of recognition
#  with minimal training
#
#- platform: dlib_face_detect
#  source:
#      - entity_id: camera.doorbird_live
