#-------------------------------------------
#  Network Related Packages
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
sensor:
  - platform: template
    sensors:
        withings_scale:
          friendly_name: 'WiThings Scale'
          value_template: "{{ 'Online' if is_state('device_tracker.withings_scale', 'home') else 'Offline' }}"

#-------------------------------------------
group:
  network:
    entities:
      - sensor.ha_installed_version
      - sensor.ha_uptime
      - sensor.since_last_boot_templated
      - sensor.disk_used_
      - sensor.speedtest_download
      - sensor.fastcom_download
      - sensor.speedtest_upload


#-------------------------------------------#-------------------------------------------
automation:
  - alias: 'Device Status'
    hide_entity: True
    trigger:
         - platform: state
           entity_id:
             - sensor.withings_scale
           to: 'offline'
           for:
             minutes: 5

    action:
      - service: script.ifttt_notify
        data_template:
          value1: 'Device Status:'
          value2: "{{ trigger.to_state.attributes.friendly_name }} is "
          value3: "{{ trigger.to_state.state }}"

      - service: script.speech_engine
        data_template:
          value1: "{{ trigger.to_state.attributes.friendly_name }} is now {{ trigger.to_state.state }}"
